apiVersion: batch/v1
kind: Job
metadata:
  name: webcrawler
  labels:
    app: webcrawler
spec:
  ttlSecondsAfterFinished: 60
  suspend: false
  completions: 3
  parallelism: 3
  template:
    metadata:
      labels:
        app: webcrawler
    spec:
      containers:
        - name: webcrawler
          image: WEBCRAWLER-IMAGE
          args:
            #- -s
            #- CLOSESPIDER_PAGECOUNT=100
            - -s
            - CLOSESPIDER_TIMEOUT=45
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
            - secretRef:
                name: rabbitmq-secret
      restartPolicy: Never
