apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: API-IMAGE
    newName: swap/api
    newTag: uuid
  - name: IDF-IMAGE
    newName: swap/idf
    newTag: uuid
  - name: INDEXER-IMAGE
    newName: swap/indexer
    newTag: uuid
  - name: WEBCRAWLER-IMAGE
    newName: swap/webcrawler
    newTag: uuid

resources:
  - manifests/api/deployment.yaml
  - manifests/api/service.yaml

  - manifests/idf/cronjob.yaml

  - manifests/indexer/configmap.yaml
  - manifests/indexer/deployment.yaml
  - manifests/indexer/service.yaml

  - manifests/postgres/configmap.yaml
  - manifests/postgres/deployment.yaml
  - manifests/postgres/service.yaml

  - manifests/rabbitmq/configmap.yaml

  - manifests/webcrawler/job.yaml

  - manifests/ingress.yaml
