apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: API-IMAGE
    newName: ronituohino/swap-search
    newTag: api
  - name: INDEXER-IMAGE
    newName: ronituohino/swap-search
    newTag: indexer

resources:
  - manifests/api/deployment.yaml
  - manifests/api/service.yaml

  - manifests/indexer/deployment.yaml
  - manifests/indexer/service.yaml

  - manifests/postgres/configmap.yaml
  - manifests/postgres/deployment.yaml
  - manifests/postgres/service.yaml

  - manifests/rabbitmq/configmap.yaml
