apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swap-dev

resources:
  - ../../base
  - namespace.yaml

  - manifests/postgres/secret.yaml

  - manifests/rabbitmq/secret.yaml
